### ISSUE TITLE
Witte titel op section "features"

### ISSUE THREAD

**Issue by Stefan-Espant** [Stefan-Espant/the-startup-responsive-interactieve-website#9]
Zorg voor een property die de titel funda geel maakt zodat deze regel voorkomen wordt:

```css
footer h1, h2, h3, h4, h5, h6, p {
  color: var(--c-default);
}
```
